config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  scope"(:locale)", locale: /es|en/ do
  resources :tasks
  resources :users
  
end

  get '/tasks/:id/mytask' => 'tasks#mytask', as: 'mytask'
  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :user
	validates :description, presence: true
	validates :title, presence: true
	validates :duration, :numericality => {:only_float => true}

validate :fecha_de_vencimiento

   def fecha_de_vencimiento
     if !finish_date.blank? and finish_date < start_date
       errors.add(:fecha_de_vencimiento, "no puede estar en el pasado")
     end
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :tasks , dependent: :destroy #para destruir las dependencias
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :mini => "40x40>" }, :default_url => "/images/:style/missing.png"
	
	validates_attachment :avatar,
	 :size => { :in => 0..10.megabytes },
	 :content_type => {:content_type => /^image\/(jpeg|png|gif|tiff)$/ }
  
          validates :username, presence: true
  		  validates :name, presence: true
  		  validates :lastname, presence: true
  		  validates :avatar, :attachment_presence => true

	def fullname
		return name + ' ' + lastname
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
 
  before_action :set_locale

 def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end

def default_url_options(options={})
  { locale: I18n.locale }
end
protected
 
	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) do |u|
	    u.permit(:username, :name, :lastname, :email, :password, :avatar, :password_confirmation)
	  end
	  devise_parameter_sanitizer.for(:account_update) do |u|
	    u.permit(:username, :name, :lastname, :email, :password, :avatar, :password_confirmation, :current_password)
	  end
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :get_users
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order("finish_date")
  end

  def mytask
    @tasks = Task.all.order(finish_date: :asc)
  end
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id 

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_users
      @users=User.all.map {|user|[user.name, user.id]}  
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :duration, :start_date, :finish_date, :user_id, :finished, :responsable)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
  def flass_class(type)
    case type
      when :success then "success"
      when :error   then "warning"
      when :alert   then "warning"
      when :notice  then ""
      else "info"
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
	def find_responsable(id)
		return User.find(id).fullname
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Trello" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

		<nav class="top-bar" data-topbar role="navigation">
		  <ul class="title-area">
		    <li class="name">
		      <h1><a href="#">Trello</a></h1>
		  </ul>

		  <section class="top-bar-section">
		    <!-- Right Nav Section -->
		    <ul class="right">

			      <% if user_signed_in? %>
			      	<li class="avatar">
		            <% if current_user.avatar.file? %>
		            <%= image_tag current_user.avatar.url(:thumb), class: "round" %>
		            <% end %>
		          </li>

			          <li>
			            <%= link_to current_user.username, edit_user_registration_path %>
			          </li>
			          <li class="active">
			            <%= link_to t('Sign Out'), destroy_user_session_path, method: :delete %>
			          </li>
	          	<% else %>
		          <li class="active">
		            <%= link_to t('Sign Up'), new_user_registration_path %>
		          </li>
		          <li>
		            <%= link_to t('Sign in'), new_user_session_path %>
		          </li>
	         	 <% end %>
		    </ul>

		    <!-- Left Nav Section -->
		   <ul class="left">
          <li><%= link_to t('User'), users_path %></li>
          <li><%= link_to t('Task'), tasks_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to t('My tasks'), mytask_path(current_user) %></li>
          <% end %>
        </ul>
		  </section>
		</nav>
	
    <div class="row">
    	<div class="large-8 columns">
    		<% flash.each do |type, message| %>
				<div data-alert class="alert-box radius <%= flass_class type %>">
				  <%= message %>
				  <a href="#" class="close">&times;</a>
				</div>
				<% end %>
    		<%= yield %>
    	</div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :finish_date %><br>
    <%= f.date_select :finish_date %>
  </div>
  <div class="field">
    <%= f.label :finished %><br>
    <%= f.check_box :finished %>
  </div>
  <div class="field">
    <%= f.label :responsable %><br>
    <%= f.select :responsable, options_for_select(@users) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task, class:"button" %> |
<%= link_to 'Back', tasks_path, class:"button" %>

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>My task</title>
</head>
<body>

<div>
  <h1>Listing tasks</h1>
  <% if user_signed_in?%>
  <%= link_to 'New Task', new_task_path, class:'button' %>
  <%end%>
</div>

<div class="row">

  <div class="large-6 columns">
    <h3>Tasks in progress</h3></a>
    <fieldset>
      <table>
          <thead>
            <tr>
            <th>Title</th>
            <th>Dur</th>
            <th>Start</th>
            <th>Finish</th>
            <th>User</th>
            <th>Responsable</th>
            <th colspan="1"></th>
            </tr>
          </thead>
            <tbody>
              <% @tasks.each do |task| %>
                <% if task.finished == false %>
                  <tr>
                  <td><%= task.title %></td>
                  <td><%= task.duration %></td>
                  <td><%= task.start_date %></td>
                  <td><%= task.finish_date %></td>
                  <td><%= task.user.fullname %></td>
                  <td><%= task.user.fullname %></td>
                  <td><%= link_to 'Show', task %></td>
                  <% if user_signed_in?%>
                  <td><%= link_to 'Edit', edit_task_path(task) %></td>
                  <td><%= link_to 'Del', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <% end %>
                  </tr>
                <% end %>
              <% end %>
          </tbody>
        </table>
        </fieldset>
    </div>

  <div class="large-6 columns">
    <h3>Tasks Completed</h3>
    <fieldset>
        <table>
          <thead>
            <tr>
            <th>Title</th>
            <th>Dur</th>
            <th>Start</th>
            <th>Finish</th>
            <th>User</th>
            <th>Responsable</th>
            <th colspan="1"></th>
            </tr>
          </thead>
            <tbody>
              <% @tasks.each do |task| %>
                <% if task.finished == true %>
                  <tr>
                  <td><%= task.title %></td>
                  <td><%= task.duration %></td>
                  <td><%= task.start_date %></td>
                  <td><%= task.finish_date %></td>
                  <td><%= task.user.fullname %></td>
                  <td><%= task.user.fullname %></td>
                  <td><%= link_to 'Show', task %></td>
                  <% if user_signed_in?%>
                    <td><%= link_to 'Edit', edit_task_path(task) %></td>
                    <td><%= link_to 'Del', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  <%end%>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
      </table>
      </fieldset>
    </div>

</div>

</body>
</html>

app/views/tasks/mytask.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>My task</title>
</head>
<body>
<div class="row">

  <div class="large-6 columns">
  <h2>Created</h2>
    <fieldset>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Dur</th>
            <th>Start</th>
            <th>Finish</th>
            <th>Done</th>
            <th>Responsable</th>
            <th colspan="1"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @tasks.each do |task| %>
          <% if task.user_id == current_user.id %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.duration %></td>
              <td><%= task.start_date %></td>
              <td><%= task.finish_date %></td>
              <td><%= task.finished %></td>
              <td><%= task.user.fullname %></td>
              <td><%= link_to 'Show', task %></td>
              <td><%= link_to 'Edit', edit_task_path(task) %></td>
              <td><%= link_to 'Del', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </fieldset>
  </div>

  <div class="large-6 columns">
    <h2>Responsable Task</h2>
    <fieldset>
      <table>
        <thead>
          <tr>
            <th>Title</th>
            <th>Dur</th>
            <th>Start</th>
            <th>Finish</th>
            <th>User</th>
            <th>Done</th>
            <th colspan="1"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @tasks.each do |task| %>
          <% if task.responsable == current_user.id %>
            <tr>
              <td><%= task.title %></td>
              <td><%= task.duration %></td>
              <td><%= task.start_date %></td>
              <td><%= task.finish_date %></td>
              <td><%= task.user.fullname %></td>
              <td><%= task.finished %></td>
              <td><%= link_to 'Show', task %></td>
              <td><%= link_to 'Edit', edit_task_path(task) %></td>
              <td><%= link_to 'Del', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </fieldset>
  </div>

</div>
	
</body>
</html>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path, class:"button" %>

app/views/tasks/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @task.duration %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @task.start_date %>
</p>

<p>
  <strong>Finish date:</strong>
  <%= @task.finish_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.user.fullname %>
</p>

<p>
  <strong>Finished:</strong>
  <%= @task.finished %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= find_responsable(@task.responsable) %>
</p>

<%= link_to 'Edit', edit_task_path(@task), class:"button" %> |
<%= link_to 'Back', tasks_path, class:"button" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
   <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user, class:"button" %> |
<%= link_to 'Back', users_path, class:"button" %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Lastname</th>
      <th>avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
		<td><%= image_tag user.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_registration_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class:"button" %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class:"button" %> |
<%= link_to 'Back', users_path, class:"button" %>